-- product/keyword/store_daily_series: allow p_to through current_date + 7
-- so Tracker / Deep Dive can request a 1-week forecast tail.
--
-- Canonical function bodies: ~/shopee_scraper/product_daily_series.sql
-- Apply on Contabo via SSH (same as listing_weekly). Do NOT
-- `supabase db push`. Live API is https://api.larisid.com (docs/self-host.md).
--
--   ssh ... docker exec -i supabase-db psql ... < product_daily_series.sql
